### ISSUE TITLE
Generate Random Strings Matching Predefined Pattern or Format for Enhanced Flexibility and Control

### ISSUE THREAD

**Issue by wuletawwonte** [Dagic-zewdu/random-string#53]
**Is your feature request related to a problem? Please describe.**
It is not possible to get a random string based on pattern or format provided. For example provide "A0" as a pattern where A represents an uppercase letter and 0 represents a digit, and get something like "H7"

**Describe the solution you'd like**
It would be nice if the package provides a method like generateWithPattern(pattern) that takes a pattern as input and generates a random string based on that pattern.

**Describe alternatives you've considered**
One possible approach could be adding pattern as an argument in the options object.

**Comment by Dagic-zewdu** [comment]
For enhancement Issues, Please have a discussion first in [discussion site](https://github.com/Dagic-zewdu/random-string/discussions).
